apiVersion: v1
kind: ConfigMap
metadata:
  name: connectivity-check-script
data:
  check.sh: |
    #!/bin/sh
    LOGFILE="/var/log/connectivity/connectivity.log"
    LAST_STATUS=""
    while true; do
      if ping -c1 -W1 8.8.8.8 >/dev/null 2>&1; then
        STATUS="up"
      else
        STATUS="down"
      fi
      if [ "$STATUS" != "$LAST_STATUS" ]; then
        echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') $STATUS" >> "$LOGFILE"
        LAST_STATUS="$STATUS"
      fi
      sleep 1
    done
